<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PDF Template</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        h1 {
            color: #333;
            text-align: center;
        }
        .content {
            margin-top: 20px;
            padding: 10px;
            border: 1px solid #333;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 12px;
            color: #777;
        }
    </style>
</head>
<body>
    <h1>PDF Generator</h1>
    <div class="content">
        <p>This is a pdf generator by leafrock</p>
        <p>Generated on : 2024-02-16 17:00:30</p>
    </div>
    <div class="footer">
        Generated by PDF Generator
    </div>
</body>
</html>
